const githubResult = """
{
  "total_count": 51463,
  "incomplete_results": false,
  "items": [
    {
      "login": "gabriel",
      "id": 2669,
      "node_id": "MDQ6VXNlcjI2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabriel",
      "html_url": "https://github.com/gabriel",
      "followers_url": "https://api.github.com/users/gabriel/followers",
      "following_url": "https://api.github.com/users/gabriel/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabriel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabriel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabriel/subscriptions",
      "organizations_url": "https://api.github.com/users/gabriel/orgs",
      "repos_url": "https://api.github.com/users/gabriel/repos",
      "events_url": "https://api.github.com/users/gabriel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabriel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Gabriel439",
      "id": 1313787,
      "node_id": "MDQ6VXNlcjEzMTM3ODc=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1313787?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Gabriel439",
      "html_url": "https://github.com/Gabriel439",
      "followers_url": "https://api.github.com/users/Gabriel439/followers",
      "following_url": "https://api.github.com/users/Gabriel439/following{/other_user}",
      "gists_url": "https://api.github.com/users/Gabriel439/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Gabriel439/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Gabriel439/subscriptions",
      "organizations_url": "https://api.github.com/users/Gabriel439/orgs",
      "repos_url": "https://api.github.com/users/Gabriel439/repos",
      "events_url": "https://api.github.com/users/Gabriel439/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Gabriel439/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielecirulli",
      "id": 886011,
      "node_id": "MDQ6VXNlcjg4NjAxMQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/886011?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielecirulli",
      "html_url": "https://github.com/gabrielecirulli",
      "followers_url": "https://api.github.com/users/gabrielecirulli/followers",
      "following_url": "https://api.github.com/users/gabrielecirulli/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielecirulli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielecirulli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielecirulli/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielecirulli/orgs",
      "repos_url": "https://api.github.com/users/gabrielecirulli/repos",
      "events_url": "https://api.github.com/users/gabrielecirulli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielecirulli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielemariotti",
      "id": 2583078,
      "node_id": "MDQ6VXNlcjI1ODMwNzg=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2583078?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielemariotti",
      "html_url": "https://github.com/gabrielemariotti",
      "followers_url": "https://api.github.com/users/gabrielemariotti/followers",
      "following_url": "https://api.github.com/users/gabrielemariotti/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielemariotti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielemariotti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielemariotti/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielemariotti/orgs",
      "repos_url": "https://api.github.com/users/gabrielemariotti/repos",
      "events_url": "https://api.github.com/users/gabrielemariotti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielemariotti/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielpconceicao",
      "id": 5131269,
      "node_id": "MDQ6VXNlcjUxMzEyNjk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5131269?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielpconceicao",
      "html_url": "https://github.com/gabrielpconceicao",
      "followers_url": "https://api.github.com/users/gabrielpconceicao/followers",
      "following_url": "https://api.github.com/users/gabrielpconceicao/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielpconceicao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielpconceicao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielpconceicao/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielpconceicao/orgs",
      "repos_url": "https://api.github.com/users/gabrielpconceicao/repos",
      "events_url": "https://api.github.com/users/gabrielpconceicao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielpconceicao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielfalcao",
      "id": 54914,
      "node_id": "MDQ6VXNlcjU0OTE0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/54914?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielfalcao",
      "html_url": "https://github.com/gabrielfalcao",
      "followers_url": "https://api.github.com/users/gabrielfalcao/followers",
      "following_url": "https://api.github.com/users/gabrielfalcao/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielfalcao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielfalcao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielfalcao/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielfalcao/orgs",
      "repos_url": "https://api.github.com/users/gabrielfalcao/repos",
      "events_url": "https://api.github.com/users/gabrielfalcao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielfalcao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielfroes",
      "id": 19231904,
      "node_id": "MDQ6VXNlcjE5MjMxOTA0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/19231904?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielfroes",
      "html_url": "https://github.com/gabrielfroes",
      "followers_url": "https://api.github.com/users/gabrielfroes/followers",
      "following_url": "https://api.github.com/users/gabrielfroes/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielfroes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielfroes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielfroes/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielfroes/orgs",
      "repos_url": "https://api.github.com/users/gabrielfroes/repos",
      "events_url": "https://api.github.com/users/gabrielfroes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielfroes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielrcouto",
      "id": 2197005,
      "node_id": "MDQ6VXNlcjIxOTcwMDU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2197005?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielrcouto",
      "html_url": "https://github.com/gabrielrcouto",
      "followers_url": "https://api.github.com/users/gabrielrcouto/followers",
      "following_url": "https://api.github.com/users/gabrielrcouto/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielrcouto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielrcouto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielrcouto/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielrcouto/orgs",
      "repos_url": "https://api.github.com/users/gabrielrcouto/repos",
      "events_url": "https://api.github.com/users/gabrielrcouto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielrcouto/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielelana",
      "id": 50211,
      "node_id": "MDQ6VXNlcjUwMjEx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/50211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielelana",
      "html_url": "https://github.com/gabrielelana",
      "followers_url": "https://api.github.com/users/gabrielelana/followers",
      "following_url": "https://api.github.com/users/gabrielelana/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielelana/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielelana/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielelana/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielelana/orgs",
      "repos_url": "https://api.github.com/users/gabrielelana/repos",
      "events_url": "https://api.github.com/users/gabrielelana/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielelana/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielPeart",
      "id": 194588,
      "node_id": "MDQ6VXNlcjE5NDU4OA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/194588?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielPeart",
      "html_url": "https://github.com/gabrielPeart",
      "followers_url": "https://api.github.com/users/gabrielPeart/followers",
      "following_url": "https://api.github.com/users/gabrielPeart/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielPeart/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielPeart/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielPeart/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielPeart/orgs",
      "repos_url": "https://api.github.com/users/gabrielPeart/repos",
      "events_url": "https://api.github.com/users/gabrielPeart/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielPeart/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GabrielFemi",
      "id": 39733548,
      "node_id": "MDQ6VXNlcjM5NzMzNTQ4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/39733548?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GabrielFemi",
      "html_url": "https://github.com/GabrielFemi",
      "followers_url": "https://api.github.com/users/GabrielFemi/followers",
      "following_url": "https://api.github.com/users/GabrielFemi/following{/other_user}",
      "gists_url": "https://api.github.com/users/GabrielFemi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GabrielFemi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GabrielFemi/subscriptions",
      "organizations_url": "https://api.github.com/users/GabrielFemi/orgs",
      "repos_url": "https://api.github.com/users/GabrielFemi/repos",
      "events_url": "https://api.github.com/users/GabrielFemi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GabrielFemi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielbull",
      "id": 671923,
      "node_id": "MDQ6VXNlcjY3MTkyMw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/671923?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielbull",
      "html_url": "https://github.com/gabrielbull",
      "followers_url": "https://api.github.com/users/gabrielbull/followers",
      "following_url": "https://api.github.com/users/gabrielbull/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielbull/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielbull/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielbull/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielbull/orgs",
      "repos_url": "https://api.github.com/users/gabrielbull/repos",
      "events_url": "https://api.github.com/users/gabrielbull/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielbull/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "s0lst1c3",
      "id": 5394955,
      "node_id": "MDQ6VXNlcjUzOTQ5NTU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5394955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s0lst1c3",
      "html_url": "https://github.com/s0lst1c3",
      "followers_url": "https://api.github.com/users/s0lst1c3/followers",
      "following_url": "https://api.github.com/users/s0lst1c3/following{/other_user}",
      "gists_url": "https://api.github.com/users/s0lst1c3/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s0lst1c3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s0lst1c3/subscriptions",
      "organizations_url": "https://api.github.com/users/s0lst1c3/orgs",
      "repos_url": "https://api.github.com/users/s0lst1c3/repos",
      "events_url": "https://api.github.com/users/s0lst1c3/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s0lst1c3/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabriel-dehan",
      "id": 1383633,
      "node_id": "MDQ6VXNlcjEzODM2MzM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1383633?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabriel-dehan",
      "html_url": "https://github.com/gabriel-dehan",
      "followers_url": "https://api.github.com/users/gabriel-dehan/followers",
      "following_url": "https://api.github.com/users/gabriel-dehan/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabriel-dehan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabriel-dehan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabriel-dehan/subscriptions",
      "organizations_url": "https://api.github.com/users/gabriel-dehan/orgs",
      "repos_url": "https://api.github.com/users/gabriel-dehan/repos",
      "events_url": "https://api.github.com/users/gabriel-dehan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabriel-dehan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielgrant",
      "id": 493968,
      "node_id": "MDQ6VXNlcjQ5Mzk2OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/493968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielgrant",
      "html_url": "https://github.com/gabrielgrant",
      "followers_url": "https://api.github.com/users/gabrielgrant/followers",
      "following_url": "https://api.github.com/users/gabrielgrant/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielgrant/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielgrant/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielgrant/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielgrant/orgs",
      "repos_url": "https://api.github.com/users/gabrielgrant/repos",
      "events_url": "https://api.github.com/users/gabrielgrant/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielgrant/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GitSquared",
      "id": 24496417,
      "node_id": "MDQ6VXNlcjI0NDk2NDE3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/24496417?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GitSquared",
      "html_url": "https://github.com/GitSquared",
      "followers_url": "https://api.github.com/users/GitSquared/followers",
      "following_url": "https://api.github.com/users/GitSquared/following{/other_user}",
      "gists_url": "https://api.github.com/users/GitSquared/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GitSquared/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GitSquared/subscriptions",
      "organizations_url": "https://api.github.com/users/GitSquared/orgs",
      "repos_url": "https://api.github.com/users/GitSquared/repos",
      "events_url": "https://api.github.com/users/GitSquared/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GitSquared/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Gabirel",
      "id": 12933851,
      "node_id": "MDQ6VXNlcjEyOTMzODUx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/12933851?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Gabirel",
      "html_url": "https://github.com/Gabirel",
      "followers_url": "https://api.github.com/users/Gabirel/followers",
      "following_url": "https://api.github.com/users/Gabirel/following{/other_user}",
      "gists_url": "https://api.github.com/users/Gabirel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Gabirel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Gabirel/subscriptions",
      "organizations_url": "https://api.github.com/users/Gabirel/orgs",
      "repos_url": "https://api.github.com/users/Gabirel/repos",
      "events_url": "https://api.github.com/users/Gabirel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Gabirel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielferreiraa",
      "id": 17201177,
      "node_id": "MDQ6VXNlcjE3MjAxMTc3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/17201177?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielferreiraa",
      "html_url": "https://github.com/gabrielferreiraa",
      "followers_url": "https://api.github.com/users/gabrielferreiraa/followers",
      "following_url": "https://api.github.com/users/gabrielferreiraa/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielferreiraa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielferreiraa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielferreiraa/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielferreiraa/orgs",
      "repos_url": "https://api.github.com/users/gabrielferreiraa/repos",
      "events_url": "https://api.github.com/users/gabrielferreiraa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielferreiraa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielfbarros",
      "id": 15388159,
      "node_id": "MDQ6VXNlcjE1Mzg4MTU5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/15388159?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielfbarros",
      "html_url": "https://github.com/gabrielfbarros",
      "followers_url": "https://api.github.com/users/gabrielfbarros/followers",
      "following_url": "https://api.github.com/users/gabrielfbarros/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielfbarros/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielfbarros/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielfbarros/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielfbarros/orgs",
      "repos_url": "https://api.github.com/users/gabrielfbarros/repos",
      "events_url": "https://api.github.com/users/gabrielfbarros/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielfbarros/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrieldarezzo",
      "id": 4562368,
      "node_id": "MDQ6VXNlcjQ1NjIzNjg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4562368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrieldarezzo",
      "html_url": "https://github.com/gabrieldarezzo",
      "followers_url": "https://api.github.com/users/gabrieldarezzo/followers",
      "following_url": "https://api.github.com/users/gabrieldarezzo/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrieldarezzo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrieldarezzo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrieldarezzo/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrieldarezzo/orgs",
      "repos_url": "https://api.github.com/users/gabrieldarezzo/repos",
      "events_url": "https://api.github.com/users/gabrieldarezzo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrieldarezzo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielflorit",
      "id": 370976,
      "node_id": "MDQ6VXNlcjM3MDk3Ng==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/370976?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielflorit",
      "html_url": "https://github.com/gabrielflorit",
      "followers_url": "https://api.github.com/users/gabrielflorit/followers",
      "following_url": "https://api.github.com/users/gabrielflorit/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielflorit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielflorit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielflorit/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielflorit/orgs",
      "repos_url": "https://api.github.com/users/gabrielflorit/repos",
      "events_url": "https://api.github.com/users/gabrielflorit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielflorit/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gbbr",
      "id": 6686356,
      "node_id": "MDQ6VXNlcjY2ODYzNTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6686356?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gbbr",
      "html_url": "https://github.com/gbbr",
      "followers_url": "https://api.github.com/users/gbbr/followers",
      "following_url": "https://api.github.com/users/gbbr/following{/other_user}",
      "gists_url": "https://api.github.com/users/gbbr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gbbr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gbbr/subscriptions",
      "organizations_url": "https://api.github.com/users/gbbr/orgs",
      "repos_url": "https://api.github.com/users/gbbr/repos",
      "events_url": "https://api.github.com/users/gbbr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gbbr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielschade",
      "id": 3276580,
      "node_id": "MDQ6VXNlcjMyNzY1ODA=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/3276580?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielschade",
      "html_url": "https://github.com/gabrielschade",
      "followers_url": "https://api.github.com/users/gabrielschade/followers",
      "following_url": "https://api.github.com/users/gabrielschade/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielschade/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielschade/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielschade/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielschade/orgs",
      "repos_url": "https://api.github.com/users/gabrielschade/repos",
      "events_url": "https://api.github.com/users/gabrielschade/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielschade/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielperales",
      "id": 1859128,
      "node_id": "MDQ6VXNlcjE4NTkxMjg=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1859128?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielperales",
      "html_url": "https://github.com/gabrielperales",
      "followers_url": "https://api.github.com/users/gabrielperales/followers",
      "following_url": "https://api.github.com/users/gabrielperales/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielperales/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielperales/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielperales/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielperales/orgs",
      "repos_url": "https://api.github.com/users/gabrielperales/repos",
      "events_url": "https://api.github.com/users/gabrielperales/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielperales/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrieldemarmiesse",
      "id": 12891691,
      "node_id": "MDQ6VXNlcjEyODkxNjkx",
      "avatar_url": "https://avatars1.githubusercontent.com/u/12891691?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrieldemarmiesse",
      "html_url": "https://github.com/gabrieldemarmiesse",
      "followers_url": "https://api.github.com/users/gabrieldemarmiesse/followers",
      "following_url": "https://api.github.com/users/gabrieldemarmiesse/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrieldemarmiesse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrieldemarmiesse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrieldemarmiesse/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrieldemarmiesse/orgs",
      "repos_url": "https://api.github.com/users/gabrieldemarmiesse/repos",
      "events_url": "https://api.github.com/users/gabrieldemarmiesse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrieldemarmiesse/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrieluizramos",
      "id": 13336905,
      "node_id": "MDQ6VXNlcjEzMzM2OTA1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13336905?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrieluizramos",
      "html_url": "https://github.com/gabrieluizramos",
      "followers_url": "https://api.github.com/users/gabrieluizramos/followers",
      "following_url": "https://api.github.com/users/gabrieluizramos/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrieluizramos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrieluizramos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrieluizramos/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrieluizramos/orgs",
      "repos_url": "https://api.github.com/users/gabrieluizramos/repos",
      "events_url": "https://api.github.com/users/gabrieluizramos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrieluizramos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielsimas",
      "id": 1619214,
      "node_id": "MDQ6VXNlcjE2MTkyMTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1619214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielsimas",
      "html_url": "https://github.com/gabrielsimas",
      "followers_url": "https://api.github.com/users/gabrielsimas/followers",
      "following_url": "https://api.github.com/users/gabrielsimas/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielsimas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielsimas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielsimas/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielsimas/orgs",
      "repos_url": "https://api.github.com/users/gabrielsimas/repos",
      "events_url": "https://api.github.com/users/gabrielsimas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielsimas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "gabrielhpugliese",
      "id": 1252818,
      "node_id": "MDQ6VXNlcjEyNTI4MTg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1252818?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gabrielhpugliese",
      "html_url": "https://github.com/gabrielhpugliese",
      "followers_url": "https://api.github.com/users/gabrielhpugliese/followers",
      "following_url": "https://api.github.com/users/gabrielhpugliese/following{/other_user}",
      "gists_url": "https://api.github.com/users/gabrielhpugliese/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gabrielhpugliese/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gabrielhpugliese/subscriptions",
      "organizations_url": "https://api.github.com/users/gabrielhpugliese/orgs",
      "repos_url": "https://api.github.com/users/gabrielhpugliese/repos",
      "events_url": "https://api.github.com/users/gabrielhpugliese/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gabrielhpugliese/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GabrielaMafra",
      "id": 18356186,
      "node_id": "MDQ6VXNlcjE4MzU2MTg2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/18356186?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GabrielaMafra",
      "html_url": "https://github.com/GabrielaMafra",
      "followers_url": "https://api.github.com/users/GabrielaMafra/followers",
      "following_url": "https://api.github.com/users/GabrielaMafra/following{/other_user}",
      "gists_url": "https://api.github.com/users/GabrielaMafra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GabrielaMafra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GabrielaMafra/subscriptions",
      "organizations_url": "https://api.github.com/users/GabrielaMafra/orgs",
      "repos_url": "https://api.github.com/users/GabrielaMafra/repos",
      "events_url": "https://api.github.com/users/GabrielaMafra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GabrielaMafra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GabrielaBezerra",
      "id": 17304151,
      "node_id": "MDQ6VXNlcjE3MzA0MTUx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/17304151?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GabrielaBezerra",
      "html_url": "https://github.com/GabrielaBezerra",
      "followers_url": "https://api.github.com/users/GabrielaBezerra/followers",
      "following_url": "https://api.github.com/users/GabrielaBezerra/following{/other_user}",
      "gists_url": "https://api.github.com/users/GabrielaBezerra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GabrielaBezerra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GabrielaBezerra/subscriptions",
      "organizations_url": "https://api.github.com/users/GabrielaBezerra/orgs",
      "repos_url": "https://api.github.com/users/GabrielaBezerra/repos",
      "events_url": "https://api.github.com/users/GabrielaBezerra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GabrielaBezerra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";